import type { Metadata } from 'next';
import './globals.css';
import { PropsWithChildren } from 'react';

import PageLoading from '@/components/sheared/PageLoading';
import { Toaster } from '@/components/ui/toaster';
import Header from 'components/sheared/Header/index';
import Providers from 'context/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Header />
          {children}
          <PageLoading />
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
