import type { Metadata } from 'next';

import './globals.css';
import { Header } from '@/components/sheared/Header';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}

        <Toaster />
      </body>
    </html>
  );
}
