import type { Metadata } from 'next';

import './globals.css';
import PageLoading from '@/components/sheared/PageLoading';
import { Toaster } from '@/components/ui/toaster';
import Header from 'components/sheared/Header/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <PageLoading />
        <Toaster />
      </body>
    </html>
  );
}
